name: icons_plus
description: A collection of popular icon packs is available in icons_plus. Such as bootstrap, font awesome, eva icons, line awesome, ionicons, and many more.
version: 3.0.0
homepage: https://rahulchouhan.me
repository: https://github.com/chouhan-rahul/icons_plus

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/flags/
    - assets/brands/

  fonts:
    - family: bootstrap
      fonts:
        - asset: assets/fonts/bootstrap.ttf
    - family: boxicons-brand
      fonts:
        - asset: assets/fonts/boxicons-brand.ttf
    - family: boxicons-regular
      fonts:
        - asset: assets/fonts/boxicons-regular.ttf
    - family: boxicons-solid
      fonts:
        - asset: assets/fonts/boxicons-solid.ttf
    - family: eva-fill
      fonts:
        - asset: assets/fonts/eva-fill.ttf
    - family: eva-outline
      fonts:
        - asset: assets/fonts/eva-outline.ttf
    - family: fontawesome
      fonts:
        - asset: assets/fonts/fontawesome.ttf
    - family: fontawesome-regular
      fonts:
        - asset: assets/fonts/fontawesome-regular.ttf
    - family: fontawesome-solid
      fonts:
        - asset: assets/fonts/fontawesome-solid.ttf
    - family: ionicons
      fonts:
        - asset: assets/fonts/ionicons.ttf
    - family: lineawesome
      fonts:
        - asset: assets/fonts/lineawesome.ttf
    - family: pixelarticons
      fonts:
        - asset: assets/fonts/pixelarticons.ttf
